# version: '3.4'

services:
  reactapp-prod:
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - stack.env
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npmdata:/data
      - npmletsencrypt:/etc/letsencrypt
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uTBzZE3u2FxWHs
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
    env_file:
      - stack.env
  # Node.js backend service
  backend:
    image: node:16 # Use the official Node.js 16 image
    container_name: node_backend
    working_dir: /app
    volumes:
      - ./backend:/app # Map the backend folder to the container
    ports:
      - "5000:5000" # Expose backend port (adjust if necessary)
    environment:
      MYSQL_HOST: 167.71.25.102:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: uTBzZE3u2FxWHs
      MYSQL_DATABASE: products
    depends_on:
      - db
    command: ["npm", "start"] # Run your backend's start command
volumes:
  npmdata:
  npmletsencrypt:
  database:



