version: '3.4'

services:
  sampleproject:
    image: sampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    depends_on:
      - sampleproject
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx:/config
    ports:
      - 80:80



