version: '3.4'

services:
  sampleproject:
    image: sampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: react-nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped


