export const PROFILES = {
     tableData: [
        {
          user_id: 1,
          first_name: "Will",
          last_name: "Burgess",
          email: "will3burgess@gmail.com",
          password: "skibiditoilet",
          shipping_address: "123 Merry Way",
          user_role: "admin",
        },
        {
          user_id: 2,
          first_name: "Jane",
          last_name: "Doe",
          email: "jane.doe@example.com",
          password: "password123",
          shipping_address: "456 Main Street",
          user_role: "customer",
        },
        {
          user_id: 3,
          first_name: "John",
          last_name: "Smith",
          email: "john.smith@example.com",
          password: "secret",
          shipping_address: "789 Oak Avenue",
          user_role: "guest",
        },
        {
          user_id: 4,
          first_name: "David",
          last_name: "Lee",
          email: "david.lee@example.com",
          password: "password456",
          shipping_address: "101 Elm Street",
          user_role: "admin",
        },
        {
          user_id: 5,
          first_name: "Emily",
          last_name: "Jones",
          email: "emily.jones@example.com",
          password: "securePass",
          shipping_address: "222 Pine Lane",
          user_role: "customer",
        },
        {
          user_id: 6,
          first_name: "Michael",
          last_name: "Brown",
          email: "michael.brown@example.com",
          password: "myPassword",
          shipping_address: "333 Cedar Road",
          user_role: "guest",
        },
        {
          user_id: 7,
          first_name: "Sarah",
          last_name: "Davis",
          email: "sarah.davis@example.com",
          password: "strongPassword",
          shipping_address: "444 Birch Court",
          user_role: "admin",
        },
        {
          user_id: 8,
          first_name: "Kevin",
          last_name: "Wilson",
          email: "kevin.wilson@example.com",
          password: "anotherPass",
          shipping_address: "555 Maple Drive",
          user_role: "customer",
        },
        {
          user_id: 9,
          first_name: "Jessica",
          last_name: "Garcia",
          email: "jessica.garcia@example.com",
          password: "yetAnotherPass",
          shipping_address: "666 Willow Way",
          user_role: "guest",
        },
        {
          user_id: 10,
          first_name: "Brian",
          last_name: "Rodriguez",
          email: "brian.rodriguez@example.com",
          password: "finalPass",
          shipping_address: "777 Oak Street",
          user_role: "admin",
        },
    ]
}